services:
  # PHP Service for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_php
    ports:
        - "9000:9000"
        - "5173:5173"
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www
    environment:
      - DATABASE_URL=mysql://username:password@mysql/${PROJECT_NAME}

  # Nginx Service for Laravel
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_webserver
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: username
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
    name: ${PROJECT_NAME}_dbdata
