services:
  # PHP Service for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mock_php
    ports:
        - "9000:9000"
        - "5173:5173"
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./supervisor/mock-worker.conf:/etc/supervisor/conf.d/supervisord.conf
      - .:/var/www
    environment:
      - DATABASE_URL=mysql://root:password@mysql/mock

  # Nginx Service for Laravel
  webserver:
    image: nginx:alpine
    container_name: mock_webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mock_mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: mock
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
